


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE SCHEMA IF NOT EXISTS "public";


ALTER SCHEMA "public" OWNER TO "pg_database_owner";


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE OR REPLACE FUNCTION "public"."rls_auto_enable"() RETURNS "event_trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'pg_catalog'
    AS $$
DECLARE
  cmd record;
BEGIN
  FOR cmd IN
    SELECT *
    FROM pg_event_trigger_ddl_commands()
    WHERE command_tag IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
      AND object_type IN ('table','partitioned table')
  LOOP
     IF cmd.schema_name IS NOT NULL AND cmd.schema_name IN ('public') AND cmd.schema_name NOT IN ('pg_catalog','information_schema') AND cmd.schema_name NOT LIKE 'pg_toast%' AND cmd.schema_name NOT LIKE 'pg_temp%' THEN
      BEGIN
        EXECUTE format('alter table if exists %s enable row level security', cmd.object_identity);
        RAISE LOG 'rls_auto_enable: enabled RLS on %', cmd.object_identity;
      EXCEPTION
        WHEN OTHERS THEN
          RAISE LOG 'rls_auto_enable: failed to enable RLS on %', cmd.object_identity;
      END;
     ELSE
        RAISE LOG 'rls_auto_enable: skip % (either system schema or not in enforced list: %.)', cmd.object_identity, cmd.schema_name;
     END IF;
  END LOOP;
END;
$$;


ALTER FUNCTION "public"."rls_auto_enable"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."ctg_assignment" (
    "asg_id" bigint NOT NULL,
    "mb_id" bigint NOT NULL,
    "rl_id" bigint NOT NULL,
    "asg_scope" character varying(20) NOT NULL,
    "pr_id" bigint,
    "asg_start_date" "date" NOT NULL,
    "asg_end_date" "date",
    "asg_is_active" boolean DEFAULT true NOT NULL,
    "asg_metadata" "jsonb" DEFAULT '{}'::"jsonb" NOT NULL,
    "asg_created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "asg_updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "ctg_assignment_scope_check" CHECK ((("asg_scope")::"text" = ANY ((ARRAY['GLOBAL'::character varying, 'PROJECTION'::character varying])::"text"[])))
);


ALTER TABLE "public"."ctg_assignment" OWNER TO "postgres";


ALTER TABLE "public"."ctg_assignment" ALTER COLUMN "asg_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."ctg_assignment_asg_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."ctg_attachment" (
    "at_id" bigint NOT NULL,
    "mb_id" bigint NOT NULL,
    "tr_id" bigint,
    "evt_id" bigint,
    "pp_id" bigint,
    "at_name" character varying(255) NOT NULL,
    "at_original_name" character varying(255),
    "at_mime_type" character varying(100),
    "at_size" bigint,
    "at_storage_path" "text" NOT NULL,
    "at_description" "text",
    "at_metadata" "jsonb" DEFAULT '{}'::"jsonb" NOT NULL,
    "at_created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "at_updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "ctg_attachment_owner_check" CHECK (((((("tr_id" IS NOT NULL))::integer + (("evt_id" IS NOT NULL))::integer) + (("pp_id" IS NOT NULL))::integer) = 1))
);


ALTER TABLE "public"."ctg_attachment" OWNER TO "postgres";


ALTER TABLE "public"."ctg_attachment" ALTER COLUMN "at_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."ctg_attachment_at_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."ctg_audit_log" (
    "al_id" bigint NOT NULL,
    "mb_id" bigint,
    "al_action" character varying(50) NOT NULL,
    "al_entity" character varying(100) NOT NULL,
    "al_entity_id" bigint,
    "al_old_data" "jsonb",
    "al_new_data" "jsonb",
    "al_metadata" "jsonb" DEFAULT '{}'::"jsonb" NOT NULL,
    "al_ip_address" character varying(100),
    "al_user_agent" "text",
    "al_created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "ctg_audit_log_action_check" CHECK ((("al_action")::"text" = ANY ((ARRAY['CREATE'::character varying, 'UPDATE'::character varying, 'DELETE'::character varying, 'VALIDATE'::character varying, 'ACTIVATE'::character varying, 'DEACTIVATE'::character varying, 'LOGIN'::character varying, 'LOGOUT'::character varying])::"text"[])))
);


ALTER TABLE "public"."ctg_audit_log" OWNER TO "postgres";


ALTER TABLE "public"."ctg_audit_log" ALTER COLUMN "al_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."ctg_audit_log_al_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."ctg_category" (
    "ct_id" bigint NOT NULL,
    "ct_code" character varying(20) NOT NULL,
    "ct_name" character varying(100) NOT NULL,
    "ct_description" "text",
    "ct_is_active" boolean DEFAULT true NOT NULL,
    "ct_metadata" "jsonb" DEFAULT '{}'::"jsonb" NOT NULL,
    "ct_created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "ct_updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."ctg_category" OWNER TO "postgres";


ALTER TABLE "public"."ctg_category" ALTER COLUMN "ct_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."ctg_category_ct_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."ctg_contribution" (
    "cr_id" bigint NOT NULL,
    "evt_id" bigint NOT NULL,
    "ct_id" bigint NOT NULL,
    "cr_expected_amount" numeric(12,2) NOT NULL,
    "cr_is_active" boolean DEFAULT true NOT NULL,
    "cr_metadata" "jsonb" DEFAULT '{}'::"jsonb" NOT NULL,
    "cr_created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "cr_updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "ctg_contribution_amount_check" CHECK (("cr_expected_amount" > (0)::numeric))
);


ALTER TABLE "public"."ctg_contribution" OWNER TO "postgres";


ALTER TABLE "public"."ctg_contribution" ALTER COLUMN "cr_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."ctg_contribution_cr_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."ctg_event" (
    "evt_id" bigint NOT NULL,
    "evt_code" character varying(50),
    "evt_title" character varying(255) NOT NULL,
    "evt_description" "text",
    "evt_scope" character varying(20) NOT NULL,
    "pr_id" bigint,
    "evt_type" character varying(50) NOT NULL,
    "evt_status" character varying(30) DEFAULT 'DRAFT'::character varying NOT NULL,
    "evt_start_at" timestamp with time zone,
    "evt_end_at" timestamp with time zone,
    "evt_created_by" bigint,
    "evt_metadata" "jsonb" DEFAULT '{}'::"jsonb" NOT NULL,
    "evt_created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "evt_updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "ctg_event_projection_scope_check" CHECK ((((("evt_scope")::"text" = 'GLOBAL'::"text") AND ("pr_id" IS NULL)) OR ((("evt_scope")::"text" = 'PROJECTION'::"text") AND ("pr_id" IS NOT NULL)))),
    CONSTRAINT "ctg_event_scope_check" CHECK ((("evt_scope")::"text" = ANY ((ARRAY['GLOBAL'::character varying, 'PROJECTION'::character varying])::"text"[]))),
    CONSTRAINT "ctg_event_status_check" CHECK ((("evt_status")::"text" = ANY ((ARRAY['DRAFT'::character varying, 'PUBLISHED'::character varying, 'ONGOING'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying])::"text"[]))),
    CONSTRAINT "ctg_event_type_check" CHECK ((("evt_type")::"text" = ANY ((ARRAY['GENERAL'::character varying, 'PARTICULAR'::character varying])::"text"[])))
);


ALTER TABLE "public"."ctg_event" OWNER TO "postgres";


ALTER TABLE "public"."ctg_event" ALTER COLUMN "evt_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."ctg_event_evt_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."ctg_event_feedback" (
    "fb_id" bigint NOT NULL,
    "evt_id" bigint NOT NULL,
    "mb_id" bigint NOT NULL,
    "fb_rating" integer,
    "fb_comment" "text",
    "fb_is_visible" boolean DEFAULT true NOT NULL,
    "fb_metadata" "jsonb" DEFAULT '{}'::"jsonb" NOT NULL,
    "fb_created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "fb_updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "ctg_event_feedback_rating_check" CHECK ((("fb_rating" IS NULL) OR (("fb_rating" >= 1) AND ("fb_rating" <= 5))))
);


ALTER TABLE "public"."ctg_event_feedback" OWNER TO "postgres";


ALTER TABLE "public"."ctg_event_feedback" ALTER COLUMN "fb_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."ctg_event_feedback_fb_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."ctg_grade" (
    "gr_id" bigint NOT NULL,
    "ct_id" bigint NOT NULL,
    "gr_group" character varying(100) NOT NULL,
    "gr_code" character varying(20) NOT NULL,
    "gr_name" character varying(150) NOT NULL,
    "gr_order" integer NOT NULL,
    "gr_is_active" boolean DEFAULT true NOT NULL,
    "gr_metadata" "jsonb" DEFAULT '{}'::"jsonb" NOT NULL,
    "gr_created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "gr_updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."ctg_grade" OWNER TO "postgres";


ALTER TABLE "public"."ctg_grade" ALTER COLUMN "gr_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."ctg_grade_gr_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."ctg_member" (
    "mb_id" bigint NOT NULL,
    "pr_id" bigint NOT NULL,
    "gr_id" bigint NOT NULL,
    "mb_auth_user_id" "uuid",
    "mb_type" character varying(20) NOT NULL,
    "mb_matricule" character varying(50),
    "mb_last_name" character varying(150) NOT NULL,
    "mb_first_name" character varying(150) NOT NULL,
    "mb_birth_date" "date",
    "mb_phone" character varying(50),
    "mb_email" character varying(255),
    "mb_photo_url" "text",
    "mb_status" character varying(30) DEFAULT 'ACTIVE'::character varying NOT NULL,
    "mb_is_active" boolean DEFAULT true NOT NULL,
    "mb_is_validated" boolean DEFAULT false NOT NULL,
    "mb_validated_by" bigint,
    "mb_validated_at" timestamp with time zone,
    "mb_metadata" "jsonb" DEFAULT '{}'::"jsonb" NOT NULL,
    "mb_created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "mb_updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "ctg_member_mb_status_check" CHECK ((("mb_status")::"text" = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying, 'SUSPENDED'::character varying, 'DECEASED'::character varying, 'ARCHIVED'::character varying])::"text"[]))),
    CONSTRAINT "ctg_member_mb_type_check" CHECK ((("mb_type")::"text" = ANY ((ARRAY['REGULAR'::character varying, 'ENCADREMENT'::character varying])::"text"[])))
);


ALTER TABLE "public"."ctg_member" OWNER TO "postgres";


ALTER TABLE "public"."ctg_member" ALTER COLUMN "mb_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."ctg_member_mb_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."ctg_notification" (
    "nt_id" bigint NOT NULL,
    "mb_id" bigint NOT NULL,
    "nt_type" character varying(50) NOT NULL,
    "nt_title" character varying(200) NOT NULL,
    "nt_message" "text" NOT NULL,
    "nt_link" "text",
    "nt_is_read" boolean DEFAULT false NOT NULL,
    "nt_read_at" timestamp with time zone,
    "nt_metadata" "jsonb" DEFAULT '{}'::"jsonb" NOT NULL,
    "nt_created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "nt_updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."ctg_notification" OWNER TO "postgres";


ALTER TABLE "public"."ctg_notification" ALTER COLUMN "nt_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."ctg_notification_nt_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."ctg_payment" (
    "py_id" bigint NOT NULL,
    "mb_id" bigint NOT NULL,
    "cr_id" bigint NOT NULL,
    "py_amount" numeric(12,2) NOT NULL,
    "py_paid_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "py_reference" character varying(100),
    "py_note" "text",
    "py_metadata" "jsonb" DEFAULT '{}'::"jsonb" NOT NULL,
    "py_created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "py_updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "ctg_payment_amount_check" CHECK (("py_amount" > (0)::numeric))
);


ALTER TABLE "public"."ctg_payment" OWNER TO "postgres";


ALTER TABLE "public"."ctg_payment" ALTER COLUMN "py_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."ctg_payment_py_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."ctg_projection" (
    "pr_id" bigint NOT NULL,
    "pr_code" character varying(50) NOT NULL,
    "pr_name" character varying(150) NOT NULL,
    "pr_description" "text",
    "pr_logo_url" "text",
    "pr_banner_url" "text",
    "pr_theme_color" character varying(20),
    "pr_is_active" boolean DEFAULT true NOT NULL,
    "pr_metadata" "jsonb" DEFAULT '{}'::"jsonb" NOT NULL,
    "pr_created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "pr_updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."ctg_projection" OWNER TO "postgres";


ALTER TABLE "public"."ctg_projection" ALTER COLUMN "pr_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."ctg_projection_pr_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."ctg_proposal" (
    "pp_id" bigint NOT NULL,
    "mb_id" bigint NOT NULL,
    "pp_scope" character varying(20) NOT NULL,
    "pr_id" bigint,
    "pp_title" character varying(200) NOT NULL,
    "pp_content" "text" NOT NULL,
    "pp_status" character varying(20) DEFAULT 'PENDING'::character varying NOT NULL,
    "pp_response" "text",
    "pp_processed_at" timestamp with time zone,
    "pp_processed_by" bigint,
    "pp_metadata" "jsonb" DEFAULT '{}'::"jsonb" NOT NULL,
    "pp_created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "pp_updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "ctg_proposal_scope_check" CHECK ((("pp_scope")::"text" = ANY ((ARRAY['GLOBAL'::character varying, 'PROJECTION'::character varying])::"text"[]))),
    CONSTRAINT "ctg_proposal_status_check" CHECK ((("pp_status")::"text" = ANY ((ARRAY['PENDING'::character varying, 'RECEIVED'::character varying, 'ACCEPTED'::character varying, 'REJECTED'::character varying])::"text"[])))
);


ALTER TABLE "public"."ctg_proposal" OWNER TO "postgres";


ALTER TABLE "public"."ctg_proposal" ALTER COLUMN "pp_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."ctg_proposal_pp_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."ctg_role" (
    "rl_id" bigint NOT NULL,
    "rl_code" character varying(50) NOT NULL,
    "rl_name" character varying(150) NOT NULL,
    "rl_type" character varying(30) NOT NULL,
    "rl_description" "text",
    "rl_is_system" boolean DEFAULT false NOT NULL,
    "rl_order" integer DEFAULT 0 NOT NULL,
    "rl_is_active" boolean DEFAULT true NOT NULL,
    "rl_metadata" "jsonb" DEFAULT '{}'::"jsonb" NOT NULL,
    "rl_created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "rl_updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."ctg_role" OWNER TO "postgres";


ALTER TABLE "public"."ctg_role" ALTER COLUMN "rl_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."ctg_role_rl_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."ctg_score" (
    "sc_id" bigint NOT NULL,
    "mb_id" bigint NOT NULL,
    "pr_id" bigint NOT NULL,
    "sc_global_score" numeric(8,2) DEFAULT 0 NOT NULL,
    "sc_projection_score" numeric(8,2) DEFAULT 0 NOT NULL,
    "sc_total_expected" numeric(14,2) DEFAULT 0 NOT NULL,
    "sc_total_paid" numeric(14,2) DEFAULT 0 NOT NULL,
    "sc_last_calculated_at" timestamp with time zone,
    "sc_metadata" "jsonb" DEFAULT '{}'::"jsonb" NOT NULL,
    "sc_created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "sc_updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "ctg_score_expected_check" CHECK (("sc_total_expected" >= (0)::numeric)),
    CONSTRAINT "ctg_score_global_check" CHECK (("sc_global_score" >= (0)::numeric)),
    CONSTRAINT "ctg_score_paid_check" CHECK (("sc_total_paid" >= (0)::numeric)),
    CONSTRAINT "ctg_score_projection_check" CHECK (("sc_projection_score" >= (0)::numeric))
);


ALTER TABLE "public"."ctg_score" OWNER TO "postgres";


ALTER TABLE "public"."ctg_score" ALTER COLUMN "sc_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."ctg_score_sc_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."ctg_setting" (
    "st_id" bigint NOT NULL,
    "st_key" character varying(100) NOT NULL,
    "st_value" "text",
    "st_description" "text",
    "st_group" character varying(50),
    "st_metadata" "jsonb" DEFAULT '{}'::"jsonb" NOT NULL,
    "st_created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "st_updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."ctg_setting" OWNER TO "postgres";


ALTER TABLE "public"."ctg_setting" ALTER COLUMN "st_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."ctg_setting_st_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."ctg_transaction" (
    "tr_id" bigint NOT NULL,
    "evt_id" bigint,
    "mb_id" bigint,
    "py_id" bigint,
    "tr_type" character varying(20) NOT NULL,
    "tr_category" character varying(50) NOT NULL,
    "tr_amount" numeric(14,2) NOT NULL,
    "tr_label" character varying(255) NOT NULL,
    "tr_description" "text",
    "tr_date" timestamp with time zone DEFAULT "now"() NOT NULL,
    "tr_metadata" "jsonb" DEFAULT '{}'::"jsonb" NOT NULL,
    "tr_created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "tr_updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "ctg_transaction_amount_check" CHECK (("tr_amount" > (0)::numeric)),
    CONSTRAINT "ctg_transaction_type_check" CHECK ((("tr_type")::"text" = ANY ((ARRAY['INCOME'::character varying, 'EXPENSE'::character varying])::"text"[])))
);


ALTER TABLE "public"."ctg_transaction" OWNER TO "postgres";


ALTER TABLE "public"."ctg_transaction" ALTER COLUMN "tr_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."ctg_transaction_tr_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."ctg_assignment"
    ADD CONSTRAINT "ctg_assignment_pkey" PRIMARY KEY ("asg_id");



ALTER TABLE ONLY "public"."ctg_attachment"
    ADD CONSTRAINT "ctg_attachment_pkey" PRIMARY KEY ("at_id");



ALTER TABLE ONLY "public"."ctg_audit_log"
    ADD CONSTRAINT "ctg_audit_log_pkey" PRIMARY KEY ("al_id");



ALTER TABLE ONLY "public"."ctg_category"
    ADD CONSTRAINT "ctg_category_ct_code_key" UNIQUE ("ct_code");



ALTER TABLE ONLY "public"."ctg_category"
    ADD CONSTRAINT "ctg_category_pkey" PRIMARY KEY ("ct_id");



ALTER TABLE ONLY "public"."ctg_contribution"
    ADD CONSTRAINT "ctg_contribution_pkey" PRIMARY KEY ("cr_id");



ALTER TABLE ONLY "public"."ctg_contribution"
    ADD CONSTRAINT "ctg_contribution_unique_event_category" UNIQUE ("evt_id", "ct_id");



ALTER TABLE ONLY "public"."ctg_event"
    ADD CONSTRAINT "ctg_event_evt_code_key" UNIQUE ("evt_code");



ALTER TABLE ONLY "public"."ctg_event_feedback"
    ADD CONSTRAINT "ctg_event_feedback_pkey" PRIMARY KEY ("fb_id");



ALTER TABLE ONLY "public"."ctg_event_feedback"
    ADD CONSTRAINT "ctg_event_feedback_unique" UNIQUE ("evt_id", "mb_id");



ALTER TABLE ONLY "public"."ctg_event"
    ADD CONSTRAINT "ctg_event_pkey" PRIMARY KEY ("evt_id");



ALTER TABLE ONLY "public"."ctg_grade"
    ADD CONSTRAINT "ctg_grade_gr_code_key" UNIQUE ("gr_code");



ALTER TABLE ONLY "public"."ctg_grade"
    ADD CONSTRAINT "ctg_grade_pkey" PRIMARY KEY ("gr_id");



ALTER TABLE ONLY "public"."ctg_member"
    ADD CONSTRAINT "ctg_member_mb_auth_user_id_key" UNIQUE ("mb_auth_user_id");



ALTER TABLE ONLY "public"."ctg_member"
    ADD CONSTRAINT "ctg_member_pkey" PRIMARY KEY ("mb_id");



ALTER TABLE ONLY "public"."ctg_notification"
    ADD CONSTRAINT "ctg_notification_pkey" PRIMARY KEY ("nt_id");



ALTER TABLE ONLY "public"."ctg_payment"
    ADD CONSTRAINT "ctg_payment_pkey" PRIMARY KEY ("py_id");



ALTER TABLE ONLY "public"."ctg_projection"
    ADD CONSTRAINT "ctg_projection_pkey" PRIMARY KEY ("pr_id");



ALTER TABLE ONLY "public"."ctg_projection"
    ADD CONSTRAINT "ctg_projection_pr_code_key" UNIQUE ("pr_code");



ALTER TABLE ONLY "public"."ctg_proposal"
    ADD CONSTRAINT "ctg_proposal_pkey" PRIMARY KEY ("pp_id");



ALTER TABLE ONLY "public"."ctg_role"
    ADD CONSTRAINT "ctg_role_pkey" PRIMARY KEY ("rl_id");



ALTER TABLE ONLY "public"."ctg_role"
    ADD CONSTRAINT "ctg_role_rl_code_key" UNIQUE ("rl_code");



ALTER TABLE ONLY "public"."ctg_score"
    ADD CONSTRAINT "ctg_score_member_unique" UNIQUE ("mb_id");



ALTER TABLE ONLY "public"."ctg_score"
    ADD CONSTRAINT "ctg_score_pkey" PRIMARY KEY ("sc_id");



ALTER TABLE ONLY "public"."ctg_setting"
    ADD CONSTRAINT "ctg_setting_key_unique" UNIQUE ("st_key");



ALTER TABLE ONLY "public"."ctg_setting"
    ADD CONSTRAINT "ctg_setting_pkey" PRIMARY KEY ("st_id");



ALTER TABLE ONLY "public"."ctg_transaction"
    ADD CONSTRAINT "ctg_transaction_pkey" PRIMARY KEY ("tr_id");



CREATE INDEX "idx_ctg_attachment_event" ON "public"."ctg_attachment" USING "btree" ("evt_id");



CREATE INDEX "idx_ctg_attachment_member" ON "public"."ctg_attachment" USING "btree" ("mb_id");



CREATE INDEX "idx_ctg_attachment_proposal" ON "public"."ctg_attachment" USING "btree" ("pp_id");



CREATE INDEX "idx_ctg_attachment_transaction" ON "public"."ctg_attachment" USING "btree" ("tr_id");



CREATE INDEX "idx_ctg_audit_log_created_at" ON "public"."ctg_audit_log" USING "btree" ("al_created_at" DESC);



CREATE INDEX "idx_ctg_audit_log_entity" ON "public"."ctg_audit_log" USING "btree" ("al_entity");



CREATE INDEX "idx_ctg_audit_log_entity_id" ON "public"."ctg_audit_log" USING "btree" ("al_entity_id");



CREATE INDEX "idx_ctg_audit_log_member" ON "public"."ctg_audit_log" USING "btree" ("mb_id");



CREATE INDEX "idx_ctg_event_feedback_event" ON "public"."ctg_event_feedback" USING "btree" ("evt_id");



CREATE INDEX "idx_ctg_event_feedback_member" ON "public"."ctg_event_feedback" USING "btree" ("mb_id");



CREATE INDEX "idx_ctg_notification_created" ON "public"."ctg_notification" USING "btree" ("nt_created_at" DESC);



CREATE INDEX "idx_ctg_notification_member" ON "public"."ctg_notification" USING "btree" ("mb_id");



CREATE INDEX "idx_ctg_notification_read" ON "public"."ctg_notification" USING "btree" ("nt_is_read");



CREATE INDEX "idx_ctg_payment_contribution" ON "public"."ctg_payment" USING "btree" ("cr_id");



CREATE INDEX "idx_ctg_payment_member" ON "public"."ctg_payment" USING "btree" ("mb_id");



CREATE INDEX "idx_ctg_payment_paid_at" ON "public"."ctg_payment" USING "btree" ("py_paid_at");



CREATE INDEX "idx_ctg_proposal_member" ON "public"."ctg_proposal" USING "btree" ("mb_id");



CREATE INDEX "idx_ctg_proposal_projection" ON "public"."ctg_proposal" USING "btree" ("pr_id");



CREATE INDEX "idx_ctg_proposal_status" ON "public"."ctg_proposal" USING "btree" ("pp_status");



CREATE INDEX "idx_ctg_score_global" ON "public"."ctg_score" USING "btree" ("sc_global_score" DESC);



CREATE INDEX "idx_ctg_score_projection" ON "public"."ctg_score" USING "btree" ("pr_id");



CREATE INDEX "idx_ctg_score_projection_score" ON "public"."ctg_score" USING "btree" ("sc_projection_score" DESC);



CREATE INDEX "idx_ctg_setting_group" ON "public"."ctg_setting" USING "btree" ("st_group");



CREATE INDEX "idx_ctg_transaction_date" ON "public"."ctg_transaction" USING "btree" ("tr_date" DESC);



CREATE INDEX "idx_ctg_transaction_event" ON "public"."ctg_transaction" USING "btree" ("evt_id");



CREATE INDEX "idx_ctg_transaction_member" ON "public"."ctg_transaction" USING "btree" ("mb_id");



CREATE INDEX "idx_ctg_transaction_payment" ON "public"."ctg_transaction" USING "btree" ("py_id");



CREATE INDEX "idx_ctg_transaction_type" ON "public"."ctg_transaction" USING "btree" ("tr_type");



ALTER TABLE ONLY "public"."ctg_assignment"
    ADD CONSTRAINT "ctg_assignment_mb_id_fkey" FOREIGN KEY ("mb_id") REFERENCES "public"."ctg_member"("mb_id");



ALTER TABLE ONLY "public"."ctg_assignment"
    ADD CONSTRAINT "ctg_assignment_pr_id_fkey" FOREIGN KEY ("pr_id") REFERENCES "public"."ctg_projection"("pr_id");



ALTER TABLE ONLY "public"."ctg_assignment"
    ADD CONSTRAINT "ctg_assignment_rl_id_fkey" FOREIGN KEY ("rl_id") REFERENCES "public"."ctg_role"("rl_id");



ALTER TABLE ONLY "public"."ctg_attachment"
    ADD CONSTRAINT "ctg_attachment_evt_id_fkey" FOREIGN KEY ("evt_id") REFERENCES "public"."ctg_event"("evt_id");



ALTER TABLE ONLY "public"."ctg_attachment"
    ADD CONSTRAINT "ctg_attachment_mb_id_fkey" FOREIGN KEY ("mb_id") REFERENCES "public"."ctg_member"("mb_id");



ALTER TABLE ONLY "public"."ctg_attachment"
    ADD CONSTRAINT "ctg_attachment_pp_id_fkey" FOREIGN KEY ("pp_id") REFERENCES "public"."ctg_proposal"("pp_id");



ALTER TABLE ONLY "public"."ctg_attachment"
    ADD CONSTRAINT "ctg_attachment_tr_id_fkey" FOREIGN KEY ("tr_id") REFERENCES "public"."ctg_transaction"("tr_id");



ALTER TABLE ONLY "public"."ctg_audit_log"
    ADD CONSTRAINT "ctg_audit_log_mb_id_fkey" FOREIGN KEY ("mb_id") REFERENCES "public"."ctg_member"("mb_id");



ALTER TABLE ONLY "public"."ctg_contribution"
    ADD CONSTRAINT "ctg_contribution_ct_id_fkey" FOREIGN KEY ("ct_id") REFERENCES "public"."ctg_category"("ct_id");



ALTER TABLE ONLY "public"."ctg_contribution"
    ADD CONSTRAINT "ctg_contribution_evt_id_fkey" FOREIGN KEY ("evt_id") REFERENCES "public"."ctg_event"("evt_id");



ALTER TABLE ONLY "public"."ctg_event"
    ADD CONSTRAINT "ctg_event_evt_created_by_fkey" FOREIGN KEY ("evt_created_by") REFERENCES "public"."ctg_member"("mb_id");



ALTER TABLE ONLY "public"."ctg_event_feedback"
    ADD CONSTRAINT "ctg_event_feedback_evt_id_fkey" FOREIGN KEY ("evt_id") REFERENCES "public"."ctg_event"("evt_id");



ALTER TABLE ONLY "public"."ctg_event_feedback"
    ADD CONSTRAINT "ctg_event_feedback_mb_id_fkey" FOREIGN KEY ("mb_id") REFERENCES "public"."ctg_member"("mb_id");



ALTER TABLE ONLY "public"."ctg_event"
    ADD CONSTRAINT "ctg_event_pr_id_fkey" FOREIGN KEY ("pr_id") REFERENCES "public"."ctg_projection"("pr_id");



ALTER TABLE ONLY "public"."ctg_grade"
    ADD CONSTRAINT "ctg_grade_ct_id_fkey" FOREIGN KEY ("ct_id") REFERENCES "public"."ctg_category"("ct_id");



ALTER TABLE ONLY "public"."ctg_member"
    ADD CONSTRAINT "ctg_member_gr_id_fkey" FOREIGN KEY ("gr_id") REFERENCES "public"."ctg_grade"("gr_id");



ALTER TABLE ONLY "public"."ctg_member"
    ADD CONSTRAINT "ctg_member_mb_validated_by_fkey" FOREIGN KEY ("mb_validated_by") REFERENCES "public"."ctg_member"("mb_id");



ALTER TABLE ONLY "public"."ctg_member"
    ADD CONSTRAINT "ctg_member_pr_id_fkey" FOREIGN KEY ("pr_id") REFERENCES "public"."ctg_projection"("pr_id");



ALTER TABLE ONLY "public"."ctg_notification"
    ADD CONSTRAINT "ctg_notification_mb_id_fkey" FOREIGN KEY ("mb_id") REFERENCES "public"."ctg_member"("mb_id");



ALTER TABLE ONLY "public"."ctg_payment"
    ADD CONSTRAINT "ctg_payment_cr_id_fkey" FOREIGN KEY ("cr_id") REFERENCES "public"."ctg_contribution"("cr_id");



ALTER TABLE ONLY "public"."ctg_payment"
    ADD CONSTRAINT "ctg_payment_mb_id_fkey" FOREIGN KEY ("mb_id") REFERENCES "public"."ctg_member"("mb_id");



ALTER TABLE ONLY "public"."ctg_proposal"
    ADD CONSTRAINT "ctg_proposal_mb_id_fkey" FOREIGN KEY ("mb_id") REFERENCES "public"."ctg_member"("mb_id");



ALTER TABLE ONLY "public"."ctg_proposal"
    ADD CONSTRAINT "ctg_proposal_pp_processed_by_fkey" FOREIGN KEY ("pp_processed_by") REFERENCES "public"."ctg_member"("mb_id");



ALTER TABLE ONLY "public"."ctg_proposal"
    ADD CONSTRAINT "ctg_proposal_pr_id_fkey" FOREIGN KEY ("pr_id") REFERENCES "public"."ctg_projection"("pr_id");



ALTER TABLE ONLY "public"."ctg_score"
    ADD CONSTRAINT "ctg_score_mb_id_fkey" FOREIGN KEY ("mb_id") REFERENCES "public"."ctg_member"("mb_id");



ALTER TABLE ONLY "public"."ctg_score"
    ADD CONSTRAINT "ctg_score_pr_id_fkey" FOREIGN KEY ("pr_id") REFERENCES "public"."ctg_projection"("pr_id");



ALTER TABLE ONLY "public"."ctg_transaction"
    ADD CONSTRAINT "ctg_transaction_evt_id_fkey" FOREIGN KEY ("evt_id") REFERENCES "public"."ctg_event"("evt_id");



ALTER TABLE ONLY "public"."ctg_transaction"
    ADD CONSTRAINT "ctg_transaction_mb_id_fkey" FOREIGN KEY ("mb_id") REFERENCES "public"."ctg_member"("mb_id");



ALTER TABLE ONLY "public"."ctg_transaction"
    ADD CONSTRAINT "ctg_transaction_py_id_fkey" FOREIGN KEY ("py_id") REFERENCES "public"."ctg_payment"("py_id");



ALTER TABLE "public"."ctg_assignment" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."ctg_attachment" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."ctg_audit_log" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."ctg_category" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."ctg_contribution" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."ctg_event" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."ctg_event_feedback" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."ctg_grade" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."ctg_member" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."ctg_notification" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."ctg_payment" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."ctg_projection" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."ctg_proposal" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."ctg_role" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."ctg_score" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."ctg_setting" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."ctg_transaction" ENABLE ROW LEVEL SECURITY;


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";



GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."ctg_assignment" TO "anon";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."ctg_assignment" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."ctg_assignment" TO "service_role";



GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."ctg_attachment" TO "anon";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."ctg_attachment" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."ctg_attachment" TO "service_role";



GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."ctg_audit_log" TO "anon";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."ctg_audit_log" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."ctg_audit_log" TO "service_role";



GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."ctg_category" TO "anon";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."ctg_category" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."ctg_category" TO "service_role";



GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."ctg_contribution" TO "anon";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."ctg_contribution" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."ctg_contribution" TO "service_role";



GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."ctg_event" TO "anon";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."ctg_event" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."ctg_event" TO "service_role";



GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."ctg_event_feedback" TO "anon";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."ctg_event_feedback" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."ctg_event_feedback" TO "service_role";



GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."ctg_grade" TO "anon";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."ctg_grade" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."ctg_grade" TO "service_role";



GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."ctg_member" TO "anon";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."ctg_member" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."ctg_member" TO "service_role";



GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."ctg_notification" TO "anon";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."ctg_notification" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."ctg_notification" TO "service_role";



GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."ctg_payment" TO "anon";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."ctg_payment" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."ctg_payment" TO "service_role";



GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."ctg_projection" TO "anon";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."ctg_projection" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."ctg_projection" TO "service_role";



GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."ctg_proposal" TO "anon";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."ctg_proposal" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."ctg_proposal" TO "service_role";



GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."ctg_role" TO "anon";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."ctg_role" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."ctg_role" TO "service_role";



GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."ctg_score" TO "anon";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."ctg_score" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."ctg_score" TO "service_role";



GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."ctg_setting" TO "anon";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."ctg_setting" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."ctg_setting" TO "service_role";



GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."ctg_transaction" TO "anon";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."ctg_transaction" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."ctg_transaction" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLES TO "service_role";







