/*
==============================================================================
 ContinGest
 Phase 2B.1
------------------------------------------------------------------------------
 Création de la table : ctg_event_modality
------------------------------------------------------------------------------
 Une modalité définit le montant de cotisation demandé à une catégorie
 pour un événement donné.

 Règle métier :
 Une modalité est toujours associée à UNE catégorie.
==============================================================================
*/

create table public.ctg_event_modality (

    md_id bigint generated by default as identity,

    evt_id bigint not null,

    ct_id bigint not null,

    md_amount numeric(12,2) not null,

    md_is_required boolean not null default true,

    md_description text,

    md_metadata jsonb not null default '{}'::jsonb,

    md_created_at timestamptz not null default now(),

    md_updated_at timestamptz not null default now(),

    --------------------------------------------------------------------------
    -- Clé primaire
    --------------------------------------------------------------------------

    constraint ctg_event_modality_pkey
        primary key (md_id),

    --------------------------------------------------------------------------
    -- Clés étrangères
    --------------------------------------------------------------------------

    constraint ctg_event_modality_event_fkey
        foreign key (evt_id)
        references public.ctg_event(evt_id)
        on delete cascade,

    constraint ctg_event_modality_category_fkey
        foreign key (ct_id)
        references public.ctg_category(ct_id),

    --------------------------------------------------------------------------
    -- Contraintes métier
    --------------------------------------------------------------------------

    constraint ctg_event_modality_amount_check
        check (md_amount >= 0),

    constraint ctg_event_modality_unique
        unique (evt_id, ct_id)

);

------------------------------------------------------------------------------
-- Index
------------------------------------------------------------------------------

create index idx_event_modality_event
    on public.ctg_event_modality(evt_id);

create index idx_event_modality_category
    on public.ctg_event_modality(ct_id);

------------------------------------------------------------------------------
-- Trigger : mise à jour automatique du champ md_updated_at
------------------------------------------------------------------------------

create trigger trg_ctg_event_modality_updated_at
before update
on public.ctg_event_modality
for each row
execute function public.ctg_set_timestamp();

------------------------------------------------------------------------------
-- Trigger : audit automatique
------------------------------------------------------------------------------

create trigger trg_ctg_event_modality_audit
after insert or update or delete
on public.ctg_event_modality
for each row
execute function public.ctg_audit_trigger('md_id');